export enum NotificationType {
  FRIEND_REQUEST = "FRIEND_REQUEST",
  FRIEND_ACCEPTED = "FRIEND_ACCEPTED",
  REMATCH_REQUEST = "REMATCH_REQUEST",
  REMATCH_ACCEPTED = "REMATCH_ACCEPTED",
  REMATCH_DECLINED = "REMATCH_DECLINED",
  GAME_WON = "GAME_WON",
  GAME_LOST = "GAME_LOST",
  GAME_TIED = "GAME_TIED",
  MATCH_REQUEST = "MATCH_REQUEST",
  MATCH_ACCEPTED = "MATCH_ACCEPTED",
  MATCH_DECLINED = "MATCH_DECLINED"
}
